### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [kucher12/firehose_project_splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kucher12** [comment]
Hi Bill, thanks for the comment. 
I have added the following line to the <head> in the application.html.erb and then re-checked on my mobile - it seems to work. Just pushed changes to github and heroku.

Good lesson for me, whenever I deploy, check the app on mobile.
